services:
  python-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python-app
    volumes:
      - ./python:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - 5000:5000

  cesharp-app:
    build:
      context: ./cesharp
      dockerfile: Dockerfile
    container_name: cesharp-app
    working_dir: /app
    volumes:
      - ./cesharp:/app
    command: dotnet run --project src/PalindromoApp